/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teladelogin;

import BancoDeDados.Administrador;
import BancoDeDados.Atendente;
import BancoDeDados.DAO;
import filavacinacao.filavacinacao;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import paginaloginatendente.TelaPrincipalAtendente;
import telaprincipal.TelaPrincipal;

/**
 *
 * @author joaot
 */
public class TelaPrincipal2 extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal2() {
    super ("Login");
    initComponents();
    setLocationRelativeTo(null);

    }
    
    private String combobox = "vazio";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        usuarioTextField = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        ComboBox = new javax.swing.JComboBox<>();

        jLabel3.setMinimumSize(new java.awt.Dimension(500, 300));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 500, 500, 500));
        setForeground(new java.awt.Color(255, 102, 0));
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(100, 100));
        setSize(new java.awt.Dimension(200, 200));
        getContentPane().setLayout(null);
        getContentPane().add(usuarioTextField);
        usuarioTextField.setBounds(210, 110, 105, 20);

        jLabel1.setText("USUARIO:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 90, 50, 14);

        jLabel2.setText("SENHA:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 140, 37, 14);

        jButton1.setText("AVANÇAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 190, 81, 23);

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(passwordField);
        passwordField.setBounds(210, 160, 105, 20);

        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um usuário", "Administrador", "Atendente" }));
        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBox);
        ComboBox.setBounds(210, 50, 150, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String login = usuarioTextField.getText();
        String senha = new String (passwordField.getPassword());
        
        if (this.combobox.equals("Administrador")) {
            
            try{
                
                Administrador usuario = new Administrador (login, senha);
                DAO dao = new DAO();
                
                if (dao.existeAdm(usuario)){
                    JOptionPane.showMessageDialog (null, "Bem vindo, " +usuario.getNome() + "!");
                    TelaPrincipal t = new TelaPrincipal();
                    t.setVisible(true);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Usuário inválido");
                }
                
            }
            catch (Exception e){
                JOptionPane.showMessageDialog (null, "Houve problemas técnicos");
                e.printStackTrace();
            }
            
        } else if (this.combobox.equals("Atendente")){
            
            try{
                
                Atendente usuario = new Atendente (login, senha);
                DAO dao = new DAO();
                
                if (dao.existeAtendente(usuario)){
                    JOptionPane.showMessageDialog (null, "Bem vindo, " +usuario.getNome() + "!");
                    filavacinacao t = new filavacinacao();
                    t.setVisible(true);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Usuário inválido");
                }
                
            }
            catch (Exception e){
                JOptionPane.showMessageDialog (null, "Houve problemas técnicos");
                e.printStackTrace();
            }
            
        } else{
            JOptionPane.showMessageDialog (null, "Você precisa selecionar um usuário primeiro");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
        String cb = ComboBox.getSelectedItem().toString();
        this.combobox = cb;
    }//GEN-LAST:event_ComboBoxActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal2().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JFormattedTextField usuarioTextField;
    // End of variables declaration//GEN-END:variables
}
